
services:
  postgres:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: apigest
      POSTGRES_PASSWORD: apigest
      POSTGRES_DB: apigest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  
volumes:
  pgdata:
